---
title: Tottenham Textiles
timezone: UTC
collections:
  feed:
    title: Feed
    output: true
    Tags:
    -
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: default
    author: Ethan
    image: ""
email: jase@jasecoop.com
description: Official website
baseurl: ''
url: http://tottenhamtextiles.github.io
twitter_username: tottenhamtextiles
github_username: jasecoop
permalink: pretty
markdown: kramdown
theme: minima
exclude:
- _app
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
