---
title: Tottenham Textiles
timezone: UTC
collections:
  feed:
    title: Feed
    output: true
    Tags:
    -
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: posts
      type: posts
    values:
      description: "is this here"
>>>>>>> 997dccc1b71896d7b00f63f31dffd6f36a13e0cc
email: jase@jasecoop.com
description: Official website
baseurl: ''
url: http://tottenhamtextiles.github.io
twitter_username: tottenhamtextiles
github_username: jasecoop
permalink: pretty
markdown: kramdown
theme: minima
exclude:
- _app
- Gemfile
- Gemfile.lock
- gulpfile.js
- node_modules
- package.json
